project/cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path('', views.home, name= "index"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
    
]

project/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name= "index"),
    path("about", views.about, name= "about")
]

project/producto/urls.py
from django.urls import path

from . import views

app_name = "producto"

urlpatterns = [
    path('', views.home, name= "index" ),
]

project/cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    def __str__(self):
          return self.nombre


class Cliente(models.Model):
        nombre = models.CharField(max_length=100)
        apellido = models.CharField(max_length=100)
        nacimiento = models.DateField(null=True, blank=True)
        pais_origen = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True )
        
        def __str__(self):
            return f"{self.nombre}{self.apellido}"
 

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models

# Create your models here.

project/cliente/views.py
from django.shortcuts import render



def home(request):
    return render(request, "cliente/index.html")

project/core/views.py
from django.shortcuts import render



def home(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, "core/about.html")

project/producto/views.py
from django.shortcuts import render



def home(request):
    return render(request, "producto/index.html")

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}     
        CLIENTE  
{% endblock contenido_titulo %}


{% block contenido %} 
    <ul>

        <li><a href="{% url 'core:index' %}">Volver al inicio</a>

    </ul>
{% endblock contenido %}

project/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Hola
{% endblock contenido_titulo %}

{% block contenido %}
    <p>Somos tuna pets</p>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>appcoder</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        {% include 'core/navbar.html' %}
 

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <h1>
            {% block contenido_titulo %}       
            {% endblock contenido_titulo %}
            </h1>
            
            {% block contenido %} 
            {% endblock contenido %}
        </div>
        {% include 'core/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{titulo}}</h2>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
    </div>
</div>

project/core/templates/core/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido_titulo %}     
        CORE  
{% endblock contenido_titulo %}


{% block contenido %} 
       <!-- Heading Row-->
       <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary" href="#!">Call to Action!</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        
        {% include 'core/card.html' with titulo="tarjeta 1" %}
        {% include 'core/card.html' with titulo="tarjeta 2" %}
        {% include 'core/card.html' with titulo="tarjeta 3" %}

    </div>
{% endblock contenido %}


    

project/core/templates/core/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Tercer PreEntrega</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Quienes somos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:index' %}">Cliente</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:index' %}">Producto</a></li>
            </ul>
        </div>
    </div>
</nav>

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}     
        PRODUCTO  
{% endblock contenido_titulo %}


{% block contenido %} 
    <ul>

        <li><a href="{% url 'core:index' %}">Volver al inicio</a>

    </ul>
{% endblock contenido %}